fix: use aspect ratio to correctly size iframes
ipfs/ipfs-blog pull request #150
Opened 2021-04-15 12:00 UTC by zebateira

The video embeds had fixed width and height, so on smaller devices the window would get an horizontal scroll. On some browsers the navigation would stick to the right completely hidden from the user.

I thought of adding the [`tailwindcss-aspect-ratio`](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) plugin, but that would require a parent element.
To fix this I simply used `aspect-ratio` property with fallback to fixed heights with one media query breakpoint.
On browsers that don't support aspect ratio, there is a specific range of screen sizes where it looks weird but for that we'd need a smaller breakpoint to get all the sizes right. But it doesn't seem to affect a lot of devices, so I think this is a good compromise. The alternative would be to add a `xs` breakpoint to target those devices.

[Browser support for `aspect-ratio`](https://caniuse.com/mdn-css_properties_aspect-ratio):

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2353186/114864912-7cb35380-9de9-11eb-99a0-01c2c094a2a0.png">

Overtime it will look better as browers implement aspect ratio.
Also centered the video on larger screens to match the behavior of the images.

## Before vs After iPhone 5S (Chrome)

<div>
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2353186/114860988-9605d100-9de4-11eb-93bf-4a089fb82b81.png">
<img width="200" alt="image" src="https://user-images.githubusercontent.com/2353186/114864607-1b8b8000-9de9-11eb-9846-a0164174a0a1.png">
</div>

## After (Other screen sizes and browsers that do not support `aspect-ratio`)

<div>
<img width="150" alt="image" src="https://user-images.githubusercontent.com/2353186/114861170-cfd6d780-9de4-11eb-9424-865c240831c3.png">
<img width="150" alt="image" src="https://user-images.githubusercontent.com/2353186/114861236-e67d2e80-9de4-11eb-96d3-d36f042ca768.png">
<img width="300" alt="image" src="https://user-images.githubusercontent.com/2353186/114861320-0280d000-9de5-11eb-868b-7444e60429b5.png">
<img width="884" alt="image" src="https://user-images.githubusercontent.com/2353186/114861411-25ab7f80-9de5-11eb-98ef-17d47193de1e.png">
</div>

2021-04-15 14:06 UTC, jdiogopeixoto requested changes
Good catch on this one! Just left one small comment.

2021-04-15 14:06 UTC, jdiogopeixoto commented on src/.vuepress/theme/layouts/BlogPost.vue
> +  @apply mx-auto;
I don't think this is necessary. It's only changing the alignment for wider screens and I think we should keep the embed videos aligned to the left for those screens. Am I missing something?

2021-04-15 14:19 UTC, jessicaschilling approved these changes
Great idea. I believe Vuepress also supports syntax like
`@[youtube](J-drqD2UebM)`
(which does some nice auto-sizing) but that isn't helpful for legacy posts that use HTML embed.

2021-04-15 14:32 UTC, zebateira commented on src/.vuepress/theme/layouts/BlogPost.vue
> +  @apply mx-auto;
As I said in the description it's just to be consistent with the images that are also centered.

2021-04-15 14:34 UTC, jdiogopeixoto commented on src/.vuepress/theme/layouts/BlogPost.vue
> +  @apply mx-auto;
Oh, I missed that. All good then 👍

2021-04-15 14:34 UTC, jdiogopeixoto approved these changes

2021-04-15 14:36 UTC, zebateira commented
> Great idea. I believe Vuepress also supports syntax like
> `@[youtube](J-drqD2UebM)`
> (which does some nice auto-sizing) but that isn't helpful for legacy posts that use HTML embed.

Yes, also if someone wants to add an embedded video with a link directly from YouTube or Vimeo it's easier to just copy and paste it.
That syntax `@[youtube](J-drqD2UebM)` is the one we taught in the forestry training?

2021-04-15 14:38 UTC, jessicaschilling commented
Yes, but I'll see if I can find somewhere apropos in the readme to note it as a reminder.

2021-04-15 15:03 UTC, cwaring commented
If possible we should enforce the embed syntax (`@[youtube](J-drqD2UebM)`) for this exact reason. We have full control of the template output then and can adjust accordingly.

Currently there is a similar issue for `pre/code` blocks too that are breaking the layout on mobile but that can be fixed easier with CSS overflow scrolling

2021-04-15 15:03 UTC, cwaring commented
The embed format comes from this plugin: https://github.com/CenterForOpenScience/markdown-it-video

2021-04-15 15:05 UTC, cwaring commented
The css patch is a nice progressive enhancement though, hopefully one day we won't need rewrites :)

2021-04-15 15:12 UTC, zebateira commented
> Currently there is a similar issue for pre/code blocks too that are breaking the layout on mobile but that can be fixed easier with CSS overflow scrolling

Will tackle that in this PR as well then 👍

2021-04-15 16:25 UTC, cwaring commented
thanks @zebateira 🙌

2021-04-16 12:19 UTC, cwaring commented
Happy to merge in as a temp fix until we decide the best way to standardise going forward. I would suggest limiting the iframe using an [attribute selector](https://www.w3schools.com/css/css_attribute_selectors.asp) though to ensure other embeds don't get affected:

Something like `iframe[src*="youtube"]` should work.

2021-04-16 14:03 UTC, zebateira commented
@cwaring updated to only target iframes on youtube and vimeo videos, nice catch!

also,

> Currently there is a similar issue for pre/code blocks too that are breaking the layout on mobile but that can be fixed easier with CSS overflow scrolling

Do you mean it breaks the layout as in the code becomes hard to read so we should not allow text wrapping and force scrolling?
Just confused if you meant the layout breaking just like the iframe was doing by adding horizontal scroll to the whole window.

2021-04-16 14:33 UTC, zebateira commented
I think I now know what you mean. The inline code blocks are indeed breaking the layout just like the iframe.
I pushed a fixed for both that and the fact that pre>code blocks not having the scroll.
How it looks now:

<img width="200" alt="image" src="https://user-images.githubusercontent.com/2353186/115039854-bd35ce80-9ec8-11eb-8649-d2fb07b2e3b4.png">

For inline code blocks, the code is wrapping now, it does not look so nice, but it's mobile where we don't expect users to take that much value from?, plus, it only happens on very small screen sizes.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/2353186/115040024-e6eef580-9ec8-11eb-8be1-8cc7779b525e.png">

/cc @jessicaschilling

2021-04-16 14:38 UTC, cwaring commented
You've got it! Sorry I'll include screenshots next time too :)

2021-04-16 14:43 UTC, merged