WIP: Hide future posts and auto publish them on speficied date
ipfs/ipfs-blog pull request #157
Opened 2021-04-19 14:53 UTC by zebateira

2021-04-20 16:52 UTC, jessicaschilling requested changes
Nice! Added a few suggested text edits for the Forestry side of things. One other note and one question:

- Most posts are going to be drafted by folks in U.S. Pacific, so it probably makes sense to run the checks at times that work closer to their hours. 4:00 UTC is 9:00 Pacific - sound OK to you?

- > Routes for link categories (events, videos, tutorials, etc) like /events will now redirect to the 404 page.

Why this?

2021-04-20 16:52 UTC, jessicaschilling commented on .forestry/front_matter/templates/newslinks.yml
> +      the future.<br>If you don''t want to schedule, just ignore this.<br><br><strong><em>WARNING</em></strong><em>:
```suggestion
      the future.<br>If you don't want to schedule, leave this blank.<br><br><strong><em>WARNING</em></strong><em>:
```

2021-04-20 16:52 UTC, jessicaschilling commented on .forestry/front_matter/templates/newslinks.yml
> +    description: '<strong>(WIP: Auto publishing feature is in the works)<br></strong><br>When
```suggestion
    description: 'When
```

2021-04-20 16:52 UTC, jessicaschilling commented on .forestry/front_matter/templates/newslinks.yml
> +      target="_blank"><em>ipfs/ipfs-blog</em></a><em> public github repo as soon as
```suggestion
      target="_blank"><em>ipfs/ipfs-blog</em></a><em> public GitHub repo as soon as
```

2021-04-20 16:52 UTC, jessicaschilling commented on .forestry/front_matter/templates/newslinks.yml
> +      you hit the save button. So any sensitive information will also be publicly
```suggestion
      you hit the Save button. This means anything you save will also be publicly
```

2021-04-20 16:52 UTC, jessicaschilling commented on .forestry/front_matter/templates/newslinks.yml
> +      available on github, but hidden from the website blog.ipfs.io.</em>'
```suggestion
      visible on GitHub, but not on the blog.ipfs.io site. Be careful if you are drafting something sensitive!</em>'
```

2021-04-20 16:59 UTC, cwaring commented
Could I suggest that we add a date field to the links too and auto populate it with the current date? It might be useful to know when they are added plus it make the interface for editors the same across all content types

2021-04-20 17:01 UTC, zebateira commented
> Most posts are going to be drafted by folks in U.S. Pacific, so it probably makes sense to run the checks at times that work closer to their hours. 4:00 UTC is 9:00 Pacific - sound OK to you?

Yap 👍  So 4am and 4pm UTC then?


> Routes for link categories (events, videos, tutorials, etc) like /events will now redirect to the 404 page.
> Why this?

It was a fix at an arm's reach so I just included it in this.
We wanted to address this issue before. ATM they are not rendering anything: https://blog.ipfs.io/events/
We might implement another fix in the future, but I think at least this small fix is welcomed.

2021-04-20 17:04 UTC, jessicaschilling commented
@cwaring The two dates are to enable us to post links to events that will happen in the near future, as a means of promoting them. Primary example of this is the monthly meetup.

@zebateira Yes please on 4am/pm UTC 😊  ... regarding link category URLs, could we not route them to their respective filter URLs, e.g. `https://blog.ipfs.io/?category=Blog%20post`?

2021-04-20 17:06 UTC, zebateira commented
@cwaring 

> Could I suggest that we add a date field to the links too and auto populate it with the current date? It might be useful to know when they are added plus it make the interface for editors the same across all content types.
>
> Having date and publish_date feels a bit odd - unless there is another reason for this that I'm missing?

Links already have a date field that is used for the date to display in the UI.
Only for events is the publish_date relevant: the "date" field for the events is the actual date when the event will happen, so we need to make a distinction there. As a bonus, this enables the other types to also have scheduling capabilities.

2021-04-20 17:07 UTC, zebateira commented
> regarding link category URLs, could we not route them to their respective filter URLs, e.g. https://blog.ipfs.io/?category=Blog%20post?

Oh ok, will try this yeah 👍

2021-04-20 17:17 UTC, zebateira commented
will defer the category pages redirect to #154 since the values will change soon.

2021-04-21 13:51 UTC, jdiogopeixoto requested changes
This is amazing, good job! 👏 

Just left some small comments.

2021-04-21 13:51 UTC, jdiogopeixoto commented on .forestry/front_matter/templates/blog-post.yml
> +    is in the works)</strong><br>To schedule this post for future publishing, simply
Shouldn't we remove this WIP notice?

2021-04-21 13:51 UTC, jdiogopeixoto commented on .forestry/front_matter/templates/blog-post.yml
> +    public github repo as soon as you hit the save button. So any sensitive information
```suggestion
    public GitHub repo as soon as you hit the save button. So any sensitive information
```

2021-04-21 13:51 UTC, jdiogopeixoto commented on .forestry/front_matter/templates/blog-post.yml
> +    will also be publicly available on github, but hidden from the website blog.ipfs.io.</em>'
```suggestion
    will also be publicly available on GitHub, but hidden from the website blog.ipfs.io.</em>'
```

2021-04-21 13:52 UTC, zebateira commented on .forestry/front_matter/templates/blog-post.yml
> +    is in the works)</strong><br>To schedule this post for future publishing, simply
```suggestion
  description: '"Published on" date.<br><br><strong><br>To schedule this post for future publishing, simply
```

2021-04-21 13:55 UTC, jdiogopeixoto approved these changes

2021-04-21 13:59 UTC, merged