feat: normalize search query
ipfs/ipfs-blog pull request #159
Opened 2021-04-21 12:57 UTC by jdiogopeixoto

- Normalizes all the fields in the search query, except the `search`
- Keeps support for the old format of categories - accessing `/?category=Blog%20post` redirects to `?/category=blog-post`

Closes #154

2021-04-21 13:30 UTC, zebateira requested changes
Nice job here! 👌

2021-04-21 13:30 UTC, zebateira commented on src/.vuepress/theme/layouts/Blog.vue
> +            subPage.tags.map((tag) => tagsArray.push(tag))
```suggestion
            tagsArray.push(...subPage.tags)
```

2021-04-21 14:39 UTC, zebateira approved these changes
👌

2021-04-21 14:41 UTC, jessicaschilling approved these changes
If @zebateira and @cwaring are good, I am too 😊  Thanks!

2021-04-21 15:02 UTC, zebateira commented
just added the change to redirect the category routes, so now `/events` should redirect to `/?category=event`.
all redirects:

- /events → /?category=event
- /videos → /?category=video
- /tutorials → /?category=tutorial
- /releasenotes → /?category=release-notes
- /newscoverage → /?category=news-coverage
- /academicpapers → /?category=academic-paper

2021-04-26 16:31 UTC, jessicaschilling commented
@zebateira @jdiogopeixoto -- how confident are you in whether it would be permissible to merge this as-is and address any future comments from @cwaring in a separate issue?

2021-04-27 13:39 UTC, zebateira commented
@jessicaschilling yeah sounds good 👍

2021-04-27 13:41 UTC, merged

2021-04-27 14:13 UTC, cwaring commented
Thanks @jdiogopeixoto, great implementation 👏🏻