feat(post): ✨ IPFS-companion MV3 update blog post.
ipfs/ipfs-blog pull request #637
Opened 2023-10-30 09:46 UTC by whizzzkid

In this PR:

- Post regarding how MV3 migration came to be.

2023-11-29 00:11 UTC, SgtPooki requested changes
This is great, just a few comments on wording that i've seen

2023-11-29 03:11 UTC, lidel reviewed
Thank you for the write-up @whizzzkid!
Some ideas/suggestions inline, but feel free to disregard/reword if needed.

2023-11-29 03:11 UTC, lidel commented on src/_blog/2023-ipfs-companion-MV3-update.md
> +MV3 changes went live towards the end of September when the collector-branch was merged to main and released on both the [chrome webstore](https://chrome.google.com/webstore/detail/ipfs-companion/nib
```suggestion
MV3 changes went live towards the end of September 2023 when the collector-branch was merged to main and released on both the [Chrome Web Store](https://chrome.google.com/webstore/detail/ipfs-companion/nibjojkomfdiaoajekhjakgkdhaomnch) and [Firefox Add-ons](https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/) we've not seen any major issues so far. The extension is working as expected and the user base is consistent. There were some minor regressions and bugs reported, but nothing that's a show-stopper. Those are being fixed as they are reported.
```

2023-11-29 03:11 UTC, lidel commented on src/_blog/2023-ipfs-companion-MV3-update.md
> +The next step will be to implement the [new Brave APIs](https://github.com/ipfs/ipfs-companion/issues/1281) which allows for finer control of the IPFS node provided in the Brave Browser. This will pr
```suggestion
The next step will be to implement the [new Brave APIs](https://github.com/ipfs/ipfs-companion/issues/1281) to allow for finer control of the IPFS node provided in the Brave Browser. This will provide a much polished experience for the users of Brave Browser that also want to enable IPFS Companion extension for additional UI and more file-grained control over redirects. There are also plans to experiment with a [Helia based built-in gateway](https://github.com/ipfs/ipfs-companion/issues/1284) on which some progress has already been made as proof-of-concepts in [helia-service-worker-gateway](https://github.com/ipfs-shipyard/helia-service-worker-gateway) and [helia-http-gateway](https://github.com/ipfs/helia-http-gateway). The learnings from these projects will be used to work with browser vendors to close API gaps and eventually implement a gateway that can be used by IPFS Companion to host an IPFS node in the browser extension itself, which will allow users to access IPFS resources when not running a local node.
```

2023-12-04 16:25 UTC, SgtPooki approved these changes
lgtm

2023-12-05 16:49 UTC, merged